version: '3'

networks:
  realtime_pipeline:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.1.0/24"

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      realtime_pipeline:
        ipv4_address: 192.168.1.2

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    hostname: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    networks:
      realtime_pipeline:
        ipv4_address: 192.168.1.3

  spark-master:
    image: bitnami/spark:3
    container_name: spark_master
    hostname: spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
    user: root
    
    networks:
      realtime_pipeline:
        ipv4_address: 192.168.1.4

  spark-worker:
    image: bitnami/spark:3
    container_name: spark_worker
    hostname: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    networks:
      realtime_pipeline:
        ipv4_address: 192.168.1.5

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    hostname: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      realtime_pipeline:
        ipv4_address: 192.168.1.6

volumes:
  mongodb_data:
    driver: local
